---
title: "DataScienceCapstone"
author: "Thomas Mey"
date: "17.3.2016"
output: html_document
---



#Set processing options
```{r}
print(paste("Directory: ",getwd()))
processing.size<-"small"
processing.percentage <- 1
processing.percentageTest <- processing.percentage / 50


```

## Download and unzip files the file to folder 'data' using R and supply smaller versions
```{r echo=FALSE}
if(!file.exists("data")) {
     dir.create("data")
}

fileurl<-"https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
dateDownloaded<-as.POSIXlt(Sys.time()) # the current time in UTC


if(!file.exists(".\\data\\Coursera-SwiftKey.zip")) {
    download.file(fileurl,destfile = ".\\data\\Coursera-SwiftKey.zip", method="auto", mode="wb")
}else {
    fileinfo<-file.info(".\\data\\Coursera-SwiftKey.zip")
    dateDownloaded<-fileinfo$mtime
}

if(!file.exists(".\\data\\final")) {
    unzip(zipfile=".\\data\\Coursera-SwiftKey.zip", exdir=".\\data")
}

if(!file.exists(".\\data\\small")) {
     dir.create(".\\data\\small")
     dir.create(".\\data\\small\\en_US")
}

if(!file.exists(".\\data\\test")) {
     dir.create(".\\data\\test")
     dir.create(".\\data\\test\\en_US")
}

directory<-paste0(".\\data\\", processing.size, "\\en_US")
nGramDirectory<-paste0(".\\data\\", processing.size, "\\NGrams")
if(!file.exists(nGramDirectory)) {
     dir.create(nGramDirectory)
}


fileurl<-"https://raw.githubusercontent.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"

if(!file.exists(".\\data\\profanity_en.txt")) {
   download.file(fileurl,destfile = ".\\data\\profanity_en.txt", method="auto", mode="w")
}
```


#produce small files
```{r}
makeSmall<-function(name,percentage,percentageTest){
    n1<-paste0(".\\data\\final\\en_US\\",name)
    n2<-paste0(".\\data\\small\\en_US\\",name)
    n3<-paste0(".\\data\\test\\en_US\\test_",name)
    

    l1<-0
    if(name == "en_US.news.txt" ) {
      readmode = "rb"
      l1<-1010242
    } else if(name == "en_US.blogs.txt" ) {
      readmode = "r"
      l1<-899288
    }else{
      l1<-2360148
      readmode = "r"
    }

    pt<-percentage+percentageTest
    if( pt < 50.0 ){
      linesToRead <- as.integer(pt / 100.0 *2 *l1)
    }
    else{
      linesToRead <-l1
    }
      
    con1<-file(n1,readmode )
    t1<-readLines(con1, n=linesToRead)
    close(con1)

    t2<-sample(t1,l1/100*percentage)
    con2<-file(n2,"w")
    writeLines(t2,con2)
    close(con2)

    t3<-sample(t1,l1/100*percentageTest)
    con3<-file(n3,"w")
    writeLines(t3,con3)
    close(con3)
}

set.seed(123)
makeSmall("en_US.twitter.txt",processing.percentage,processing.percentageTest)
makeSmall("en_US.blogs.txt",processing.percentage,processing.percentageTest)
makeSmall("en_US.news.txt",processing.percentage,processing.percentageTest)

print(paste0("Built training and test set with ", processing.percentage, "% training and ",processing.percentageTest ,"% test."  ))

```

