---
title: "TestPredictionQuality"
author: "Thomas Mey"
date: "13. April 2016"
output: html_document
---


## setup environment
```{r}
library(data.table)
library(dplyr)
library(tm) 
require(quanteda)

source("commonProcess.R")
source("WordPredictionApp/Common.r")
```

## read profanity
```{r }
p<-readProfanity()
``` 


```{r}
buildTestSet<-function(directory,p,samplesize) {
    #build test string and match
    #build and cleanse test corpus
    docs <- Corpus(DirSource(directory))
    docs<-preprocess(docs,p)
    
    docs[[3]]$content[1]
    length(docs[[1]]$content)
    length(docs[[2]]$content)
    length(docs[[3]]$content)
    
    corpus_df <- data.frame(text=lapply(docs[1], '[',"content"), stringsAsFactors=F)
    corpus_df <- rbind(corpus_df,data.frame(text=lapply(docs[2], '[',"content"), stringsAsFactors=F))
    corpus_df <- rbind(corpus_df,data.frame(text=lapply(docs[3], '[',"content"), stringsAsFactors=F))
    
    corpus_df<-corpus_df$content
    corpus_df[19]
    length(corpus_df)
    
    #build sample stings
    numberOfStingsToSample<-samplesize / 5
    set.seed(1234)
    
    n<-sample(length(corpus_df),numberOfStingsToSample)
    testset<-corpus_df[n]

    tt<-{}
    for(i in 1:numberOfStingsToSample) {
      t<-testset[i]
      s<-gregexpr(" ",t)
      v<-s[[1]]
      w<-v[(min(3,length(v))) :length(v)]
      t1<-t(data.frame(lapply(w, function(x) {
        x<-substr(t,0,x-1)
        g <- regexpr("\\ [^\\ ]*$", x)
        c(substring(x,0,g-1),trimws(substring(x,g)))
      })))
      
      colnames(t1)<-c("test","match")
      rownames(t1)<-NULL
      tt<-rbind(tt,t1)
    }

    tt[1:samplesize,]
}
```

 

```{r}
options(mc.cores=2)
samplesize<-10000

tt<-buildTestSet(makeFileName(dir.root,dir.test),p,samplesize)

head(tt)

testresults<-data.frame()
testRun<-1
i<-1
for(i in 1:length(percentages)) {
    #Read NGrams
    percentage<-percentages[i]
    nGramDirectory<-makeFileName(dir.root,percentage,dir.ngrams)
    nGramDirectory<-substr(nGramDirectory,3,10000L)
    
    j<-4
    for(j in 1:length(ngramFile1Test)){ 
      if(j<4){
          n1GramTable<-read1GramTable(nGramDirectory,ngramFile1Test[j])
          n2GramTable<-readNGramTable(nGramDirectory,ngramFile2Test[j])
          n3GramTable<-readNGramTable(nGramDirectory,ngramFile3Test[j])
          
      }   
      else
      {
         n1GramTable<-read1GramTable(nGramDirectory,ngramFile1Test[j])
         n2GramTable<-readNGramDataTable(nGramDirectory,ngramFile2Test[j])
         n3GramTable<-readNGramDataTable(nGramDirectory,ngramFile3Test[j])
      }
      
      #test...
      ptm <- proc.time()
      print(paste("Processing items:",dim(tt)[1]))
      r<-NULL
      k<-1
      for(k in 1:dim(tt)[1]) {
        res<-predictWord(n1GramTable,n2GramTable,n3GramTable ,as.character(tt[k,1]),6,ngramFileCollapse[j])
        r1<-tt[k,2]  %in% res
        if(debug.print){
          print(paste("item:",i))
          print(paste("Match:", tt[k,2]))
          print(res)
          print(r1)
        }
        r<-c(r,r1)
      }
      tm<-proc.time() - ptm
      
      
      rt<-table(r==TRUE)
      
      pq<-rt[2]/length(r)*100
      print(paste("NGram table sizes (3,2,1):",nrow(n3GramTable),nrow(n2GramTable),nrow(n1GramTable)))
      print(paste("Number of test strings:",samplesize))
      print(paste("Number of samples:",length(r)))
      print("Matches:")
      print(rt)
      print(paste("prediction quality:",pq,"%"))
      print("Time consumed:")
      print(tm)
      print("Time consumed per prediction(ms):")
      print(tm[3]/length(r)*1000    )
 
      testresults[testRun,1]<-percentage
      testresults[testRun,2]<-j
      testresults[testRun,3]<-nrow(n1GramTable)
      testresults[testRun,4]<-nrow(n2GramTable)
      testresults[testRun,5]<-nrow(n3GramTable)

      testresults[testRun,6]<-rt[2]
      testresults[testRun,7]<-length(r)
      testresults[testRun,8]<-pq
      testresults[testRun,9]<-tm[3]/length(r)*1000 
      colnames(testresults)<-c("percentage","variant","n1","n2","n3", "matches","samples","pq","ms")
      
      createDir(makeFileName(dir.root,dir.testresults))
      write.csv(testresults,file=makeFileName(dir.root,dir.testresults,"testresults.csv "))
      
      
      testRun<-testRun+1
    }
}

```

    
